import type { Move } from '../data'

const DESCRIPTIONS: Record<string, string> = {
  EFFECT_NORMAL_HIT: 'Inflicts regular damage with no additional effect.',
  EFFECT_SLEEP: 'Puts the target to sleep.',
  EFFECT_POISON_HIT: 'Has a CHANCE% chance to poison the target.',
  EFFECT_LEECH_HIT: 'Drains half the damage inflicted to heal the user.',
  EFFECT_BURN_HIT: 'Has a CHANCE% chance to burn the target.',
  EFFECT_FREEZE_HIT: 'Has a CHANCE% chance to freeze the target.',
  EFFECT_PARALYZE_HIT: 'Has a CHANCE% chance to paralyze the target.',
  EFFECT_SELFDESTRUCT: 'User faints.',
  EFFECT_DREAM_EATER: 'Only works on sleeping Pokémon. Drains half the damage inflicted to heal the user.',
  EFFECT_MIRROR_MOVE: "Uses the target's last used move.",
  EFFECT_ATTACK_UP: "Raises the user's Attack by one stage.",
  EFFECT_DEFENSE_UP: "Raises the user's Defense by one stage.",
  EFFECT_SPEED_UP: "Raises the user's Speed by one stage.",
  EFFECT_SP_ATK_UP: "Raises the user's Special Attack by one stage.",
  EFFECT_SP_DEF_UP: "Raises the user's Special Defense by one stage.",
  EFFECT_ACCURACY_UP: "Raises the user's accuracy by one stage.",
  EFFECT_EVASION_UP: "Raises the user's evasion by one stage.",
  EFFECT_ALWAYS_HIT: 'Never misses.',
  EFFECT_ATTACK_DOWN: "Lowers the target's Attack by one stage.",
  EFFECT_DEFENSE_DOWN: "Lowers the target's Defense by one stage.",
  EFFECT_SPEED_DOWN: "Lowers the target's Speed by one stage.",
  EFFECT_SP_ATK_DOWN: "Lowers the target's Special Attack by one stage.",
  EFFECT_SP_DEF_DOWN: "Lowers the target's Special Defense by one stage.",
  EFFECT_ACCURACY_DOWN: "Lowers the target's accuracy by one stage.",
  EFFECT_EVASION_DOWN: "Lowers the target's evasion by one stage.",
  EFFECT_RESET_STATS: "Resets all Pokémon's stats, accuracy, and evasion.",
  EFFECT_BIDE: 'User waits for two turns, then hits back for twice the damage it took.',
  EFFECT_RAMPAGE: 'Hits every turn for 2-3 turns, then confuses the user.',
  EFFECT_FORCE_SWITCH: 'Immediately ends wild battles. Forces trainers to switch Pokémon.',
  EFFECT_MULTI_HIT: 'Hits 2-5 times in one turn.',
  EFFECT_CONVERSION: "User's type changes to the type of one of its moves at random.",
  EFFECT_FLINCH_HIT: 'Has a CHANCE% chance to make the target flinch.',
  EFFECT_HEAL: 'Heals the user by half its max HP.',
  EFFECT_TOXIC: 'Badly poisons the target, inflicting more damage every turn.',
  EFFECT_PAY_DAY: "Scatters money on the ground worth five times the user's level.",
  EFFECT_LIGHT_SCREEN: 'Reduces damage from special attacks by 50% for five turns.',
  EFFECT_TRI_ATTACK: 'Has a CHANCE% chance to burn, freeze, or paralyze the target.',
  EFFECT_OHKO: 'Causes a one-hit KO.',
  EFFECT_RAZOR_WIND: 'Requires a turn to charge before attacking.',
  EFFECT_SUPER_FANG: "Inflicts damage equal to half the target's HP.",
  EFFECT_STATIC_DAMAGE: 'Inflicts BASE_POWER points of damage.',
  EFFECT_TRAP_TARGET: 'Prevents the target from fleeing and inflicts damage for 2-5 turns.',
  EFFECT_DOUBLE_HIT: 'Hits twice in one turn.',
  EFFECT_JUMP_KICK: 'If the user misses, it takes half the damage it would have inflicted in recoil.',
  EFFECT_MIST: "Protects the user's stats from being changed by enemy moves.",
  EFFECT_FOCUS_ENERGY: "	Increases the user's chance to score a critical hit.",
  EFFECT_RECOIL_HIT: 'User receives 1/4 the damage it inflicts in recoil.',
  EFFECT_CONFUSE: 'Confuses the target.',
  EFFECT_ATTACK_UP_2: "Raises the user's Attack by two stages.",
  EFFECT_DEFENSE_UP_2: "Raises the user's Defense by two stages.",
  EFFECT_SPEED_UP_2: "Raises the user's Speed by two stages.",
  EFFECT_SP_ATK_UP_2: "Raises the user's Special Attack by two stages.",
  EFFECT_SP_DEF_UP_2: "Raises the user's Special Defense by two stages.",
  EFFECT_ACCURACY_UP_2: "Raises the user's accuracy by two stages.",
  EFFECT_EVASION_UP_2: "Raises the user's evasion by two stages.",
  EFFECT_TRANSFORM: 'User becomes a copy of the target until it leaves battle.',
  EFFECT_ATTACK_DOWN_2: "Lowers the target's Attack by two stages.",
  EFFECT_DEFENSE_DOWN_2: "Lowers the target's Defense by two stages.",
  EFFECT_SPEED_DOWN_2: "Lowers the target's Speed by two stages.",
  EFFECT_SP_ATK_DOWN_2: "Lowers the target's Special Attack by two stages.",
  EFFECT_SP_DEF_DOWN_2: "Lowers the target's Special Defense by two stages.",
  EFFECT_ACCURACY_DOWN_2: "Lowers the target's accuracy by two stages.",
  EFFECT_EVASION_DOWN_2: "Lowers the target's evasion by two stages.",
  EFFECT_REFLECT: 'Reduces damage from physical attacks by half.',
  EFFECT_POISON: 'Poisons the target.',
  EFFECT_PARALYZE: 'Paralyzes the target.',
  EFFECT_ATTACK_DOWN_HIT: "Has a CHANCE% chance to lower the target's Attack by one stage.",
  EFFECT_DEFENSE_DOWN_HIT: "Has a CHANCE% chance to lower the target's Defense by one stage.",
  EFFECT_SPEED_DOWN_HIT: "Has a CHANCE% chance to lower the target's Speed by one stage.",
  EFFECT_SP_ATK_DOWN_HIT: "Has a CHANCE% chance to lower the target's Special Attack by one stage.",
  EFFECT_SP_DEF_DOWN_HIT: "Has a CHANCE% chance to lower the target's Special Defense by one stage.",
  EFFECT_ACCURACY_DOWN_HIT: "Has a CHANCE% chance to lower the target's accuracy by one stage.",
  EFFECT_EVASION_DOWN_HIT: "Has a CHANCE% chance to lower the target's evasion by one stage.",
  EFFECT_SKY_ATTACK: 'User charges for one turn before attacking. Has a CHANCE% chance to make the target flinch.',
  EFFECT_CONFUSE_HIT: 'Has a CHANCE% chance to confuse the target.',
  EFFECT_POISON_MULTI_HIT: 'Hits twice in the same turn. Has a CHANCE% chance to poison the target.',
  EFFECT_SUBSTITUTE:
    "Transfers 1/4 of the user's max HP into a doll, protecting the user from further damage or status changes until it breaks.",
  EFFECT_HYPER_BEAM: 'User foregoes its next turn to recharge.',
  EFFECT_RAGE: 'If the user is hit after using this move, its Attack rises by one stage.',
  EFFECT_MIMIC: "Copies the target's last used move.",
  EFFECT_METRONOME: 'Randomly selects and uses any move in the game.',
  EFFECT_LEECH_SEED: 'Seeds the target, stealing HP from it every turn.',
  EFFECT_SPLASH: 'Does nothing.',
  EFFECT_DISABLE: "Disables the target's last used move for 1-8 turns.",
  EFFECT_LEVEL_DAMAGE: "Inflicts damage equal to the user's level.",
  EFFECT_PSYWAVE: "Inflicts damage between 50% and 150% of the user's level.",
  EFFECT_COUNTER: 'Inflicts twice the damage the user received from the last physical hit it took.',
  EFFECT_ENCORE: 'Forces the target to repeat its last used move every turn for 2 to 6 turns.',
  EFFECT_PAIN_SPLIT: "Sets the user's and targets's HP to the average of their current HP.",
  EFFECT_SNORE: 'Has a CHANCE% chance to make the target flinch. Only works if the user is sleeping.',
  EFFECT_CONVERSION2:
    "Changes the user's type to a random type either resistant or immune to the last move used against it.",
  EFFECT_LOCK_ON: "Ensures that the user's next move will hit the target.",
  EFFECT_SKETCH: "Permanently becomes the target's last used move.",
  EFFECT_SLEEP_TALK: "Randomly uses one of the user's other three moves. Only works if the user is sleeping.",
  EFFECT_DESTINY_BOND: 'If the user faints this turn, the target automatically will, too.',
  EFFECT_REVERSAL: 'Inflicts more damage when the user has less HP remaining, with a maximum of 200 power.',
  EFFECT_SPITE: "Lowers the PP of the target's last used move by 2 to 5.",
  EFFECT_FALSE_SWIPE: "Cannot lower the target's HP below 1.",
  EFFECT_HEAL_BELL: 'Cures the entire party of major status effects.',
  EFFECT_PRIORITY_HIT:
    'Quick Attack inflicts damage. It has a priority of +1, so it is used before all moves that do not have increased priority.',
  EFFECT_TRIPLE_KICK: 'Hits three times, increasing power by 100% with each successful hit.',
  EFFECT_THIEF: "Takes the target's item.",
  EFFECT_MEAN_LOOK: 'Prevents the target from leaving battle.',
  EFFECT_NIGHTMARE: "Target loses 1/4 its max HP every turn as long as it's asleep.",
  EFFECT_FLAME_WHEEL: 'Has a CHANCE% chance to burn the target. Lets frozen Pokémon thaw themselves.',
  EFFECT_CURSE:
    'Ghosts pay half their max HP to hurt the target every turn. Others decrease Speed but raise Attack and Defense.',
  EFFECT_PROTECT: 'Prevents any moves from hitting the user this turn.',
  EFFECT_SPIKES: 'Scatters Spikes, hurting opposing Pokémon that switch in.',
  EFFECT_FORESIGHT:
    "Forces the target to have no Evade, and allows it to be hit by Normal and Fighting moves even if it's a Ghost.",
  EFFECT_PERISH_SONG: 'User and target both faint after three turns.',
  EFFECT_SANDSTORM: 'Changes the weather to a sandstorm for five turns.',
  EFFECT_ENDURE: "Prevents the user's HP from lowering below 1 this turn.",
  EFFECT_ROLLOUT:
    'Power doubles every turn this move is used in succession after the first, resetting after five turns.',
  EFFECT_SWAGGER: "Raises the target's Attack by two stages and confuses the target.",
  EFFECT_FURY_CUTTER:
    'Power doubles every turn this move is used in succession after the first, maxing out after five turns.',
  EFFECT_ATTRACT:
    'Target falls in love if it has the opposite gender, and has a 50% chance to refuse attacking the user.',
  EFFECT_RETURN: 'Power increases with happiness, up to a maximum of 102.',
  EFFECT_PRESENT: 'Randomly inflicts damage with power from 40 to 120 or heals the target for 1/4 its max HP.',
  EFFECT_FRUSTRATION: 'Power increases as happiness decreases, up to a maximum of 102.',
  EFFECT_SAFEGUARD: "Protects the user's field from major status ailments and confusion for five turns.",
  EFFECT_SACRED_FIRE: 'Has a CHANCE% chance to burn the target. Lets frozen Pokémon thaw themselves.',
  EFFECT_MAGNITUDE: 'Power varies randomly from 10 to 150.',
  EFFECT_BATON_PASS: 'Allows the trainer to switch out the user and pass effects along to its replacement.',
  EFFECT_PURSUIT: 'Has double power against, and can hit, Pokémon attempting to switch out.',
  EFFECT_RAPID_SPIN: 'Frees the user from binding moves, removes Leech Seed, and blows away Spikes.',
  EFFECT_MORNING_SUN: 'Heals the user by half its max HP. Affected by weather.',
  EFFECT_SYNTHESIS: 'Heals the user by half its max HP. Affected by weather.',
  EFFECT_MOONLIGHT: 'Heals the user by half its max HP. Affected by weather.',
  EFFECT_HIDDEN_POWER: "Power and type depend upon user's IVs. Power can range from 30 to 70.",
  EFFECT_RAIN_DANCE: 'Changes the weather to rain for five turns.',
  EFFECT_SUNNY_DAY: 'Changes the weather to sunny for five turns.',
  EFFECT_DEFENSE_UP_HIT: "Has a CHANCE% chance to raise the user's Defense by one stage.",
  EFFECT_ATTACK_UP_HIT: "Has a CHANCE% chance to raise the user's Attack by one stage.",
  EFFECT_ALL_UP_HIT: "Has a CHANCE% chance to raise all of the user's stats by one stage.",
  EFFECT_BELLY_DRUM: 'User pays half its max HP to max out its Attack.',
  EFFECT_PSYCH_UP: "Discards the user's stat changes and copies the target's.",
  EFFECT_MIRROR_COAT: 'Inflicts twice the damage the user received from the last special hit it took.',
  EFFECT_SKULL_BASH: "Raises the user's Defense by one stage. User charges for one turn before attacking.",
  EFFECT_TWISTER: 'Has a CHANCE% chance to make the target flinch.',
  EFFECT_EARTHQUAKE: 'Inflicts regular damage and can hit Dig users.',
  EFFECT_FUTURE_SIGHT: 'Hits the target two turns later.',
  EFFECT_GUST: 'Inflicts regular damage and can hit Pokémon in the air.',
  EFFECT_STOMP: 'Has a CHANCE% chance to make the target flinch.',
  EFFECT_SOLARBEAM: 'Requires a turn to charge before attacking.',
  EFFECT_THUNDER: 'Has a CHANCE% chance to paralyze the target.',
  EFFECT_TELEPORT: 'Immediately ends wild battles. No effect otherwise.',
  EFFECT_BEAT_UP: 'Hits once for every conscious Pokémon the trainer has.',
  EFFECT_FLY: 'User dodges all attacks for one turn before attacking.',
  EFFECT_DEFENSE_CURL: "Raises user's Defense by one stage.",
}

export function effectDescription(move: Move): string {
  if (DESCRIPTIONS[move.effect] == null) {
    throw new Error(`No description for effect ${move.effect}`)
  }

  return DESCRIPTIONS[move.effect]
    .replace('CHANCE%', `${move.effectChance}%`)
    .replace('BASE_POWER', `${move.basePower}`)
}
